export const paginationUserList = (item) => ({
  bio: item.bio,
  createdAt: item.createdAt,
  displayName: item.displayName,
  avatarUrl: item.avatarUrl,
  authProvider: item.authProvider,
  email: item.email,
  followersCount: item.followersCount,
  followingCount: item.followingCount,
  isVerified: item.isVerified,
  lastLogin: item.lastLogin,
  oauthProviders: item.oauthProviders,
  onboardingCompleted: item.onboardingCompleted,
  preferences: item.preferences,
  role: item.role,
  socialLinks: item.socialLinks,
  status: item.status,
  postsCount: item.postsCount,
  savedCount: item.savedCount,
  loginAttempts: item.loginAttempts,
  lockUntil: item.lockUntil,
  updatedAt: item.updatedAt,
  username: item.username,
  _id: item._id
})