export enum CategoriaComidaEnum {
  // 🍔 Tipos de establecimiento
  RESTAURANTE_FAMILIAR = 'restaurante_familiar',
  RESTAURANTE_GOURMET = 'restaurante_gourmet',
  COMIDA_RAPIDA = 'comida_rapida',
  COMIDA_CALLEJERA = 'comida_callejera',
  COCINA_DE_AUTOR = 'cocina_de_autor',
  CAFETERIA = 'cafeteria',
  CAFETERIA_ASIAN = 'cafeteria_asian',
  BAR = 'bar',
  LOUNGE = 'lounge',
  TABERNA = 'taberna',
  CANTINA = 'cantina',
  FOOD_TRUCK = 'food_truck',
  BUFFET = 'buffet',
  MERCADO_GOURMET = 'mercado_gourmet',
  FOOD_MARKET = 'food_market',
  PANADERIA = 'panaderia',
  REPOSTERIA = 'reposteria',
  HELADERIA = 'heladeria',
  SMOOTHIES = 'smoothies',

  // 🍽️ Tipos de cocina
  MEXICANA = 'mexicana',
  ITALIANA = 'italiana',
  MEDITERRANEA = 'mediterranea',
  ASIATICA = 'asiatica',
  JAPONESA = 'japonesa',
  COREANA = 'coreana',
  CHINA = 'china',
  TAILANDESA = 'tailandesa',
  INDIA = 'india',
  AMERICANA = 'americana',
  ESPANOLA = 'espanola',
  ARGENTINA = 'argentina',
  FRANCESA = 'francesa',
  PERUANA = 'peruana',
  FUSION = 'fusion',

  // 🌱 Estilos o enfoques
  VEGETARIANA = 'vegetariana',
  VEGANA = 'vegana',
  SALUDABLE = 'saludable',
  ORGANICA = 'organica',
  CARNES = 'carnes_parrilla',
  MARISQUERIA = 'marisqueria',
  ASADOR = 'asador',
  PIZZERIA = 'pizzeria',
  HAMBURGUESA = 'hamburguesas',
  TACOS = 'taqueria',
  SUSHI = 'sushi',
  POSTRES = 'postres',
  DESAYUNOS = 'desayunos_brunch',
  ESPECIALIDADES = 'especialidades',
}